name: project_mmh
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_form_builder: ^10.0.1
  flutter_local_notifications: ^19.5.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.2
  font_awesome_flutter: ^10.9.1
  form_builder_validators: ^11.2.0
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  google_fonts: ^7.0.2
  image_picker: ^1.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  table_calendar: ^3.2.0
  uuid: ^4.5.2
  modal_bottom_sheet: ^3.0.0
  cupertino_calendar_picker: ^2.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/klinik-icon.png"
  min_sdk_android: 21

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#fc4391"
  image: "lib/assets/klinik-icon.png"
  branding: "lib/assets/klinik-branding.png"

  android_12:
    color: "#fc4391"
    image: "lib/assets/klinik-icon.png"
    branding: "lib/assets/klinik-branding.png"


flutter:
  uses-material-design: true
  assets:
    - lib/assets/klinik-icon.png
